### ISSUE TITLE
Setup and Update scripts

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/rails_apps_composer#19]
### Main Idea
Scripts for `setup` and `update` of current projects' state.

### Purpose
- `Setup` script: Newcomers can setup app without challenges
- `Update` script: Everyday development comes easier when you have script that can update your app to latest stable state

### Changes

* [x] Base `bin/setup` script:
- Install gems
- Run migrations
- ...

```ruby
#!/usr/bin/env ruby
require "pathname"
require "fileutils"
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path("../../", __FILE__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  puts "== Installing dependencies =="
  system! "gem install bundler --conservative"
  system("bundle check") || system!("bundle install --path vendor/bundle")

  puts "\n== Preparing database =="
  system! "bin/rails db:setup"

  puts "\n== DONE =="
end
```

* [x] Base `bin/update` script:
- Install gems
- Run migrations
- Remove old logs and tmp
- ...

```ruby
#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'
include FileUtils

# path to your application root.
APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

chdir APP_ROOT do
  puts "== Installing dependencies =="
  system! "gem install bundler --conservative"
  system("bundle check") || system!("bundle install --path vendor/bundle")

  puts "\n== Updating database =="
  system! 'bin/rails db:migrate'

  puts "\n== Removing old logs and tempfiles =="
  system! 'bin/rails log:clear tmp:clear'

  puts "\n== DONE =="
end
```

### Examples 
* [Setup script](https://github.com/datarockets/bevital/blob/master/bin/setup) 
* [Update script](https://github.com/datarockets/bevital/blob/master/bin/update)
* [Updated setup and update scripts(not approved)](https://github.com/datarockets/bevital/pull/17/files#diff-80c8811098fc38c15812045ab8e96412)

###### P.S. Ping me if you are not agree, or have better idea.

**Comment by roman-dubrovsky** [comment]
@AleksSenkou 👍

**Comment by MProG** [comment]
@AleksSenkou Whats problem with current version? I see only `--path vendor/bundle`.
 clean logs in setup normal

**Comment by AleksSenkou** [comment]
> I see only --path vendor/bundle, clean logs in setup normal

@MProG yeah, lets change it

**Comment by AleksSenkou** [comment]
@MProG Seems like you've finished here
