### ISSUE TITLE
API // Documentation

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/rails_apps_composer#22]
### Main idea

Add documentation for endpoints

### Suggestion

We can use [apipie-rails](https://github.com/Apipie/apipie-rails)
I didn't have issues with this gem

Should be added as default(we can choose another gem too)

### Changes

* [x] Add `gem 'apipie-rails'`

* [x] Run generator `rails g apipie:install`

* [x] Add base initializer to `config/initializers/apipie.rb` with content:
```ruby
Apipie.configure do |config|
  config.app_name = "App name" # should be real app name
  config.validate = false
  config.process_params = false
  config.api_base_url = "/api"
  config.doc_base_url = "/apidoc"
  config.namespaced_resources = true

  config.api_controllers_matcher = "#{Rails.root}/app/controllers/api/**/*.rb"
end
```

* [x] Add routes for apipie to `routes.rb`
```ruby
apipie unless Rails.env.production?
```

see [here](https://github.com/datarockets/bevital/blob/master/config/routes.rb)

* [x] We can add tip to README that `apipie` is used for API documentation

###### P.S. Ping me if you are not agree, or have better idea.

**Comment by MProG** [comment]
@AleksSenkou  I think apipie-rails is not cool. For this gem we should add  many code for controllers.

**Comment by AleksSenkou** [comment]
@MProG which gem would you chose?

**Comment by MProG** [comment]
@AleksSenkou I dont now. Now i investigating this problem.
