### ISSUE TITLE
API // Web server

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/rails_apps_composer#24]
### Main

Puma is already default server 👍 

### Changes

* [x] Add `config/examples/puma.rb` file with content:
```ruby
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i
threads threads_count, threads_count

port ENV.fetch("API_PORT") { 3001 }

environment ENV.fetch("RAILS_ENV") { "development" }

plugin :tmp_restart
```

* [x] Add `config/puma.rb` file to `.gitignore`

* [x] Update `bin/setup` and `bin/update` scripts with
```ruby
unless File.exist?("config/puma.rb")
    cp "config/examples/puma.rb", "config/puma.rb"
end
```

###### P.S. Ping me if you are not agree, or have better idea.

**Comment by MProG** [comment]
https://github.com/datarockets/rails_apps_composer/pull/27
