### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/rails_apps_composer#33]
### Main idea

Move validations to forms

### Suggestion

We can use [Reform](https://github.com/trailblazer/reform) forms for the purpose.

### Changes

* [x] Add `gem 'reform-rails', '~> 0.1'`

* [x] Add folder `app/forms` with `.keep` file within it.

* [x] Add `gem 'virtus'`

**Comment by AleksSenkou** [comment]
@MProG @roman-dubrovsky guys, can you please update this issue with your knowledge about `Virtus` and forms. Share your experience please.

**Comment by roman-dubrovsky** [comment]
@AleksSenkou why did yoy add version specifier `~> 0.1` for reform gem? It's a very old version. The last reform version is 2.1.

**Comment by AleksSenkou** [comment]
@roman-dubrovsky this version specified for `reform-rails` gem 😉 
```
reform-rails (0.1.7)
      activemodel (>= 3.2)
      reform (>= 2.2.0)
```

**Comment by MProG** [comment]
@AleksSenkou
